version: '3.9'

services:
  easyfood-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: easyfood-server
    ports:
      - "4000:3000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    command: node dist/main.js
    # For development, you can use:
    # command: npm run start:dev

  easyfood-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: easyfood-client
    ports:
      - "4001:80"
    env_file:
      - ./client/.env
    depends_on:
      - easyfood-server
