version: '3.9'

services:
  easyfood-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: easyfood-server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    command: node dist/main.js
    # For development, you can use:
    # command: npm run start:dev

  easyfood-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: easyfood-client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - easyfood-server
